#!/usr/bin/env python3
"""Karaoke-Fassung pro Song suchen: das von YouTube automatisch erzeugte
Studio-Audio ("Interpret - Topic", Beschreibung "Auto-generated by YouTube").
Diese Fassung ist exakt die Aufnahme, auf die LRCLIB-Zeitstempel passen --
das Musikvideo (Feld 'yt') hat oft andere Intros/Pausen, deshalb lief der
Karaoke-Text bisher selten synchron.

Ablauf je Song (eindeutig nach Interpret|Titel ueber alle */songs.json):
  1. LRCLIB fragen (gleiche Bereinigung wie ccLyricsClean in shared/
     decades.js). Kein synchroner Text -> fertig, YouTube wird nicht gefragt.
  2. YouTube-Suche (2 Formulierungen), Kandidaten: Kanal ~ Interpret, Titel ~ Titel, Laenge
     hoechstens +-3 s neben einer LRCLIB-Fassung.
  3. Bester Kandidat wird einzeln geprueft: "Auto-generated by YouTube" und
     playable_in_embed.

Ergebnis:
  karaoke/videos.json  {"<a>|<t>": {"yk": <video-id>, "d": <sekunden>}}
                       (laedt die Seite, sobald Karaoke an ist)
  karaoke/status.json  {"<a>|<t>": [<ergebnis>, "<datum>"]} -- was schon
                       versucht wurde; kein_text/kein_topic nach
                       RETRY_DAYS erneut, fehler beim naechsten Lauf.
songs.json wird NICHT angefasst (keine Konflikte mit den anderen Workflows).

Reihenfolge: meistgesehene Songs zuerst (Feld vc). Zeitbudget pro Lauf,
Zwischenspeichern, Schutzschalter: nach MAX_FEHLER_IN_FOLGE YouTube-Fehlern
hintereinander (z.B. Bot-Sperre) bricht der Lauf ab statt weiterzuhaemmern.

Aufruf: python3 tools/fetch_karaoke_videos.py [--limit N]
"""
import argparse
import datetime
import glob
import json
import os
import random
import re
import subprocess
import time
import unicodedata
import urllib.error
import urllib.parse
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "karaoke")
VIDEOS_PATH = os.path.join(OUT_DIR, "videos.json")
STATUS_PATH = os.path.join(OUT_DIR, "status.json")

USER_AGENT = "DriftwareCatalogBot/1.0 +https://driftware.online"
TIME_BUDGET_SECONDS = int(os.environ.get("KARAOKE_TIME_BUDGET_SECONDS", "18000"))  # 5h
SAVE_EVERY = 20
RETRY_DAYS = 90
DURATION_TOLERANCE = 3.0
MAX_FEHLER_IN_FOLGE = 8
START_TS = time.time()
TODAY = datetime.date.today().isoformat()


def load_json(path, default):
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    return default


def save_json(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(data, f, separators=(",", ":"), ensure_ascii=False, sort_keys=True)
    os.replace(tmp, path)


# ------------------------------------------------------------ Normalisierung

def lyrics_clean(s):
    """Wie ccLyricsClean in shared/decades.js."""
    s = re.sub(r"\s*[\(\[][^\)\]]*[\)\]]", "", str(s or ""))
    s = re.sub(r"\s+-\s+.*$", "", s)
    s = re.sub(r"\s+(feat\.?|ft\.?|featuring)\s+.*$", "", s, flags=re.IGNORECASE)
    return s.strip()


def lyrics_artist(a):
    """Wie ccLyricsFetch: nur der erste Interpret."""
    return lyrics_clean(re.split(r",|&| x | und ", str(a or ""), flags=re.IGNORECASE)[0])


def norm(s):
    s = unicodedata.normalize("NFKD", s or "")
    s = "".join(ch for ch in s if not unicodedata.combining(ch)).lower().replace("&", "and")
    s = s.rstrip("*")
    s = re.sub(r"\s*\(\d+\)\s*$", "", s)
    if s.startswith("the "):
        s = s[4:]
    return "".join(ch for ch in s if ch.isalnum())


def song_key(s):
    return f"{s.get('a')}|{s.get('t')}"  # identisch zu ccLyricsSongKey


# ------------------------------------------------------------ LRCLIB

def lrclib_durations(artist, title):
    q = urllib.parse.urlencode({"track_name": lyrics_clean(title), "artist_name": lyrics_artist(artist)})
    req = urllib.request.Request("https://lrclib.net/api/search?" + q, headers={"User-Agent": USER_AGENT})
    for attempt in range(4):
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                data = json.loads(resp.read().decode("utf-8"))
            return sorted({round(x["duration"]) for x in data
                           if x.get("syncedLyrics") and not x.get("instrumental") and x.get("duration")})
        except urllib.error.HTTPError as e:
            if e.code == 429 or e.code >= 500:
                time.sleep(5 * (attempt + 1))
                continue
            return None
        except Exception:
            time.sleep(3 * (attempt + 1))
    return None


# ------------------------------------------------------------ YouTube

class YouTubeFehler(Exception):
    pass


def yt_json(args, timeout=60):
    try:
        p = subprocess.run(["yt-dlp", *args, "-J", "--no-warnings", "--skip-download"],
                           capture_output=True, text=True, timeout=timeout)
    except subprocess.TimeoutExpired:
        raise YouTubeFehler("Zeitueberschreitung")
    if p.returncode != 0 or not p.stdout.strip():
        err = (p.stderr or "").strip().splitlines()
        raise YouTubeFehler(err[-1][:200] if err else f"Exit {p.returncode}")
    return json.loads(p.stdout)


def find_topic_video(artist, title, durations):
    a_key = norm(lyrics_artist(artist))
    t_key = norm(lyrics_clean(title))
    # 1. Versuch "... topic"; bei grossen Stars verdraengen Fan-Uploads das
    # Studio-Audio, dann 2. Versuch ueber dessen Beschreibungstext.
    for query in (f"ytsearch10:{lyrics_artist(artist)} {lyrics_clean(title)} topic",
                  f'ytsearch10:"{lyrics_clean(title)}" {lyrics_artist(artist)} "provided to youtube by"'):
        hit = _pick(yt_json([query, "--flat-playlist"]), a_key, t_key, durations)
        if hit:
            return hit
        time.sleep(random.uniform(0.5, 1.0))
    return None


def _pick(res, a_key, t_key, durations):
    cands = []
    for e in res.get("entries") or []:
        ch = norm(re.sub(r"\s*-\s*topic$", "", e.get("channel") or e.get("uploader") or "", flags=re.IGNORECASE))
        et = norm(lyrics_clean(e.get("title")))
        dur = e.get("duration")
        if not e.get("id") or not dur or not ch or not et:
            continue
        artist_ok = ch == a_key or (len(ch) > 3 and len(a_key) > 3 and (ch in a_key or a_key in ch))
        if not artist_ok or et != t_key:
            continue  # Studio-Audio traegt den nackten Titel, ohne "Interpret - "
        diff = min(abs(dur - d) for d in durations)
        if diff <= DURATION_TOLERANCE:
            cands.append((diff, -(e.get("view_count") or 0), e["id"], dur))
    for diff, _, vid, dur in sorted(cands)[:2]:
        info = yt_json([f"https://www.youtube.com/watch?v={vid}"])
        if "Auto-generated by YouTube" in (info.get("description") or "") and info.get("playable_in_embed", True):
            return {"yk": vid, "d": int(info.get("duration") or dur)}
        time.sleep(random.uniform(0.5, 1.0))
    return None


# ------------------------------------------------------------ Ablauf

def collect_songs():
    """Eindeutige Songs ueber alle Seiten, meistgesehene zuerst."""
    songs = {}
    for path in glob.glob(os.path.join(ROOT, "*-music", "songs.json")):
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        lists = data.values() if isinstance(data, dict) else [data]
        for lst in lists:
            if not isinstance(lst, list):
                continue
            for s in lst:
                if not isinstance(s, dict) or not s.get("a") or not s.get("t") or not s.get("yt"):
                    continue
                k = song_key(s)
                if k not in songs or (s.get("vc") or 0) > (songs[k].get("vc") or 0):
                    songs[k] = s
    return sorted(songs.values(), key=lambda s: -(s.get("vc") or 0))


def due(entry):
    if not entry:
        return True
    result, date = entry
    if result == "ok":
        return False
    if result == "fehler":
        return True
    try:
        age = (datetime.date.today() - datetime.date.fromisoformat(date)).days
    except ValueError:
        return True
    return age >= RETRY_DAYS


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--limit", type=int, default=0, help="hoechstens N Songs (0 = bis Zeitbudget)")
    args = ap.parse_args()

    videos = load_json(VIDEOS_PATH, {})
    status = load_json(STATUS_PATH, {})
    songs = collect_songs()
    todo = [s for s in songs if due(status.get(song_key(s)))]
    print(f"{len(songs)} Songs gesamt, {len(videos)} mit Karaoke-Fassung, {len(todo)} offen.")

    counts = {"ok": 0, "kein_text": 0, "kein_topic": 0, "fehler": 0}
    fehler_in_folge = 0
    done = 0
    for s in todo:
        if time.time() - START_TS > TIME_BUDGET_SECONDS:
            print("Zeitbudget erreicht, Rest folgt im naechsten Lauf.")
            break
        if args.limit and done >= args.limit:
            break
        k = song_key(s)
        durations = lrclib_durations(s["a"], s["t"])
        if durations is None:
            result = "fehler"
        elif not durations:
            result = "kein_text"
        else:
            try:
                hit = find_topic_video(s["a"], s["t"], durations)
                fehler_in_folge = 0
                if hit:
                    videos[k] = hit
                    result = "ok"
                else:
                    result = "kein_topic"
            except YouTubeFehler as e:
                fehler_in_folge += 1
                print(f"  YouTube-Fehler ({fehler_in_folge}/{MAX_FEHLER_IN_FOLGE}): {e}")
                result = "fehler"
            time.sleep(random.uniform(1.0, 2.0))  # YouTube nicht stressen
        status[k] = [result, TODAY]
        counts[result] += 1
        done += 1
        extra = f" -> {videos[k]['yk']} ({videos[k]['d']} s)" if result == "ok" else ""
        print(f"[{done}] {s['a']} - {s['t']}: {result}{extra}")
        if done % SAVE_EVERY == 0:
            save_json(VIDEOS_PATH, videos)
            save_json(STATUS_PATH, status)
        if fehler_in_folge >= MAX_FEHLER_IN_FOLGE:
            print("::warning::Zu viele YouTube-Fehler hintereinander (Sperre?) -- Lauf wird beendet, naechster Lauf macht weiter.")
            break
        time.sleep(0.3)  # LRCLIB schonen

    save_json(VIDEOS_PATH, videos)
    save_json(STATUS_PATH, status)
    rest = sum(1 for x in songs if due(status.get(song_key(x))))
    print(f"\nFertig fuer diesen Lauf: {done} bearbeitet {counts}. "
          f"Karaoke-Fassungen gesamt: {len(videos)}. Noch offen: {rest}.")


if __name__ == "__main__":
    main()
